// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sentry
{
    public partial class ClientKey : Pulumi.CustomResource
    {
        [Output("dateCreated")]
        public Output<string?> DateCreated { get; private set; } = null!;

        [Output("dsnCSP")]
        public Output<string?> DsnCSP { get; private set; } = null!;

        [Output("dsnPublic")]
        public Output<string?> DsnPublic { get; private set; } = null!;

        [Output("dsnSecret")]
        public Output<string?> DsnSecret { get; private set; } = null!;

        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        [Output("public")]
        public Output<string?> Public { get; private set; } = null!;

        [Output("secret")]
        public Output<string?> Secret { get; private set; } = null!;


        /// <summary>
        /// Create a ClientKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClientKey(string name, ClientKeyArgs args, CustomResourceOptions? options = null)
            : base("sentry:index:ClientKey", name, args ?? new ClientKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ClientKey(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sentry:index:ClientKey", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "dsnSecret",
                    "secret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ClientKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ClientKey Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ClientKey(name, id, options);
        }
    }

    public sealed class ClientKeyArgs : Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("organizationSlug", required: true)]
        public Input<string> OrganizationSlug { get; set; } = null!;

        [Input("projectSlug", required: true)]
        public Input<string> ProjectSlug { get; set; } = null!;

        public ClientKeyArgs()
        {
        }
    }
}
