# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "default_client_key_dsn_public": "defaultClientKeyDSNPublic",
    "default_environment": "defaultEnvironment",
    "organization_slug": "organizationSlug",
    "subject_prefix": "subjectPrefix",
    "subject_template": "subjectTemplate",
    "team_slug": "teamSlug",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "defaultClientKeyDSNPublic": "default_client_key_dsn_public",
    "defaultEnvironment": "default_environment",
    "organizationSlug": "organization_slug",
    "subjectPrefix": "subject_prefix",
    "subjectTemplate": "subject_template",
    "teamSlug": "team_slug",
}
