name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:      
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code
      uses: actions/checkout@v2

    - name: Check SDK consistency
      run: ./ci/test-sdk-is-consistent-with-schema

    - name: Run tests
      run: go test ./...
